Heatmap homepage
edemagbenyo/smashing-magazine-teardown pull request #1
Opened 2019-10-01 19:21 UTC by edemagbenyo

Things learnt:
Position with grid

2019-10-01 20:31 UTC, Forison reviewed
# Pull request under review by Addo

2019-10-01 20:42 UTC, Forison requested changes
# Good Job Guys on your first attempt, am impressed👌👌
I nearly approved your project😇😇😇
Project well organized and uses semantic HTML, keep it up👌👌👋👋
Here are a few changes I would like us to work on😔
- It contains centered links (content is not important).
> I can't find the centered links in your footer
note > links can be random lorem ipsum text
![Screenshot from 2019-09-24 16-11-11](https://user-images.githubusercontent.com/29695661/65999041-980a7800-e46a-11e9-9d0f-7961e1c52ac1.png)


- You should fix the warnings given to you by the[ validator ](https://validator.w3.org)when uploading the index file.🙂
> you can replace the ```article``` with ```div``` or give each ```article``` a heading here you use lorem ipsum for dummy texts. I prefer you to use the second option in this case.

Reminder use more descriptive messages in pr description
## That is it Guys, Do the changes and submit for review.
Happy coding🙂🙂

2019-10-02 09:39 UTC, collinsugwu commented
What this PR does
1 a tag added to the links section
2 h tags added to the articles

2019-10-02 13:53 UTC, stratospherique requested changes
### Nice job implemented the suggested changes :clap: . However, the fixes that you applied are not exactly what my colleague suggested. check below :arrow_down: 

- You added an `<a>` elements in the footer, however, you need to add some text inside to make them visually apparent (i.e. they are invisible).

- The html validator warnings persists also. :pray: fix them.
  - You can use headings (e.g h2) instead of `<p>` elements inside the article elements.

### That's it :relaxed: . When finished, kindly resubmit another code review request :pray:

2019-10-02 16:55 UTC, whiz25 commented on index.html
> +                <li><a href="#">posts</a></li>
![Screenshot from 2019-10-02 19-52-28](https://user-images.githubusercontent.com/19773024/66064631-6f5bae80-e54e-11e9-8b68-e51415b51af1.png)


These links still don't appear. Please make them visible and properly centered.

2019-10-02 16:56 UTC, whiz25 requested changes
## Good job :+1: 
Please make the suggested change in the comment and re-submit for another PR.

2019-10-02 17:45 UTC, whiz25 approved these changes
## Bravo!
At this point, this project is complete and so I give you a :+1:

2019-10-02 18:57 UTC, merged